### ISSUE TITLE
Shaw Trajectory

### ISSUE THREAD

**Issue by swarnimshukla** [msultan/tica_metadynamics_paper_1#6]
Hi, can you tell me where I can find the Shaw trajectory files??

**Comment by msultan** [comment]
You need to email DESERES directly to get access to the trajectory. I can't share them since its under their copyright.

**Comment by swarnimshukla** [comment]
can you please share the email id with me?
Thanks a lot for the help

**Comment by msultan** [comment]
its on their [website](https://www.deshawresearch.com/contact.html)
